### ISSUE TITLE
Incredibly slow compilation times

### ISSUE THREAD

**Issue by babylard** [YendisFish/Polarbear#5]
It barely functions. It literally took an hour to complete. I dont know wharts wrong.

**Comment by YendisFish** [comment]
show cod

**Comment by stormyhs** [comment]
At least you got it to run. These devs dont care at all about their users. I'm reporting the repository.

**Comment by YendisFish** [comment]
:trollface: SoonDB infiltration was devastating

**Comment by babylard** [comment]
These damn skids
